require('lazy').setup('plugins', {
	defaults = { lazy = true },
	ui = { border = 'rounded' },
	performance = {
		rtp = {
			disabled_plugins = {
				'2html_plugin',
				'getscript',
				'getscriptPlugin',
				'gzip',
				'logipat',
				'loaded_remote_plugins',
				'loaded_tutor_mode_plugin',
				'matchit',
				'matchparen',
				'netrw',
				'netrwFileHandlers',
				'netrwPlugin',
				'netrwSettings',
				'rrhelper',
				'spec',
				'spellfile_plugin',
				'tar',
				'tarPlugin',
				'tohtml',
				'tutor',
				'vimball',
				'vimballPlugin',
				'zip',
				'zipPlugin',
			},
		},
	},
})
